name: Vibration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Test Light Vibration
      run: python vibrate.py --intensity light
    
    - name: Test Medium Vibration
      run: python vibrate.py --intensity medium --count 2
    
    - name: Test Heavy Vibration
      run: python vibrate.py --intensity heavy
    
    - name: Test Pattern
      run: python vibrate.py --pattern light,medium,heavy,medium,light
    
    - name: Show Help
      run: python vibrate.py --help